var slideData = {
    slide:[
        {
            image:'1_1.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'false'
        },
        {
            image:'1_slide.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'false'
        },
        {
            image:'1_2.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'false'
        },
        {
            image:'1_3.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'false'
        },
        {
            image:'1_4.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'true'
        },
        {
            image:'2_slide.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'false'
        },
        {
            image:'2_1.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'false'
        },
        {
            image:'2_2.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'false'
        },
        {
            image:'2_3.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'true'
        },
        {
            image:'2_4.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'true'
        },
        {
            image:'2_5.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'false'
        },
        {
            image:'2_6.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'false'
        },
        {
            image:'2_7.jpg',
            background:'1.jpg',
            hand:'1.png',
            istimer:'true'
        },
        {
            image:'3_slide.jpg',
            background:'2.jpg',
            hand:'2.png',
            istimer:'false'
        },
        {
            image:'3_1.jpg',
            background:'2.jpg',
            hand:'2.png',
            istimer:'false'
        },
        {
            image:'3_2.jpg',
            background:'2.jpg',
            hand:'2.png',
            istimer:'true'
        },
        {
            image:'3_3.jpg',
            background:'2.jpg',
            hand:'2.png',
            istimer:'false'
        },
        {
            image:'3_4.jpg',
            background:'2.jpg',
            hand:'2.png',
            istimer:'true'
        },
        {
            image:'3_5.jpg',
            background:'2.jpg',
            hand:'2.png',
            istimer:'false'
        },
        {
            image:'3_6.jpg',
            background:'2.jpg',
            hand:'2.png',
            istimer:'true'
        },
        {
            image:'3_7.jpg',
            background:'2.jpg',
            hand:'2.png',
            istimer:'true'
        },
        {
            image:'3_8.jpg',
            background:'2.jpg',
            hand:'2.png',
            istimer:'false'
        },
        {
            image:'3_9.jpg',
            background:'2.jpg',
            hand:'2.png',
            istimer:'true'
        },
        {
            image:'4_slide.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'false'
        },
        {
            image:'4_1.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'false'
        },
        {
            image:'4_2.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'false'
        },
        {
            image:'4_3.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'true'
        },
        {
            image:'4_4.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'false'
        },
        {
            image:'4_5.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'false'
        },
        {
            image:'4_6.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'true'
        },
        {
            image:'4_7.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'false'
        },
        {
            image:'4_8.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'true'
        },
        {
            image:'4_9.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'true'
        },
        {
            image:'4_10.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'false'
        },
        {
            image:'4_11.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'true'
        },
        {
            image:'4_12.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'true'
        },
        {
            image:'4_13.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'false'
        },
        {
            image:'4_14.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'false'
        },
        {
            image:'4_15.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'false'
        },
        {
            image:'4_16.jpg',
            background:'3.jpg',
            hand:'3.png',
            istimer:'true'
        },
        {
            image:'5_slide.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'false'
        },
        {
            image:'5_1.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'false'
        },
        {
            image:'5_2.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'false'
        },
        {
            image:'5_3.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'true'
        },
        {
            image:'5_4.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'false'
        },
        {
            image:'5_5.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'true'
        },
        {
            image:'5_6.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'false'
        },
        {
            image:'5_7.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'false'
        },
        {
            image:'5_8.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'true'
        },
        {
            image:'5_9.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'true'
        },
        {
            image:'5_10.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'false'
        },
        {
            image:'5_11.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'true'
        },
        {
            image:'5_12.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'true'
        },
        {
            image:'5_13.jpg',
            background:'4.jpg',
            hand:'4.png',
            istimer:'false'
        },
        {
            image:'6_slide.jpg',
            background:'5.jpg',
            hand:'5.png',
            istimer:'false'
        },
        {
            image:'1_5.jpg',
            background:'5.jpg',
            hand:'5.png',
            istimer:'true'
        },
        {
            image:'1_6.jpg',
            background:'5.jpg',
            hand:'5.png',
            istimer:'false'
        },
        {
            image:'1_7.jpg',
            background:'5.jpg',
            hand:'5.png',
            istimer:'false'
        },
        {
            image:'7_slide.jpg',
            background:'6.jpg',
            hand:'6.png',
            istimer:'false'
        },
        {
            image:'6_1.jpg',
            background:'6a.jpg',
            hand:'6.png',
            istimer:'true'
        },
        {
            image:'6_2.jpg',
            background:'6b.jpg',
            hand:'6.png',
            istimer:'false'
        },
        {
            image:'6_3.jpg',
            background:'6b.jpg',
            hand:'6.png',
            istimer:'true'
        },
        {
            image:'6_4.jpg',
            background:'6c.jpg',
            hand:'6.png',
            istimer:'false'
        },
        {
            image:'6_5.jpg',
            background:'6c.jpg',
            hand:'6.png',
            istimer:'true'
        },
        {
            image:'6_6.jpg',
            background:'6d.jpg',
            hand:'6.png',
            istimer:'false'
        },
        {
            image:'6_7.jpg',
            background:'6d.jpg',
            hand:'6.png',
            istimer:'true'
        },
        {
            image:'6_8.jpg',
            background:'6e.jpg',
            hand:'6.png',
            istimer:'false'
        },
        {
            image:'6_9.jpg',
            background:'6e.jpg',
            hand:'6.png',
            istimer:'true'
        },
        {
            image:'6_10.jpg',
            background:'6f.jpg',
            hand:'6.png',
            istimer:'false'
        },
        {
            image:'6_11.jpg',
            background:'6f.jpg',
            hand:'6.png',
            istimer:'true'
        },
        {
            image:'6_12.jpg',
            background:'6g.jpg',
            hand:'6.png',
            istimer:'false'
        },
        {
            image:'6_13.jpg',
            background:'6g.jpg',
            hand:'6.png',
            istimer:'true'
        },
        {
            image:'6_14.jpg',
            background:'6h.jpg',
            hand:'6.png',
            istimer:'false'
        },
        {
            image:'6_15.jpg',
            background:'6h.jpg',
            hand:'6.png',
            istimer:'true'
        },
        {
            image:'6_16.jpg',
            background:'6i.jpg',
            hand:'6.png',
            istimer:'false'
        },
        {
            image:'6_17.jpg',
            background:'6i.jpg',
            hand:'6.png',
            istimer:'true'
        },
        {
            image:'6_18.jpg',
            background:'6j.jpg',
            hand:'6.png',
            istimer:'false'
        },
        {
            image:'6_19.jpg',
            background:'6.jpg',
            hand:'6.png',
            istimer:'true'
        },
        {
            image:'8_slide.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'false'
        },
        {
            image:'7_1.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'true'
        },
        {
            image:'7_2.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'false'
        },
        {
            image:'7_3.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'false'
        },
        {
            image:'7_4.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'true'
        },
        {
            image:'7_5.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'true'
        },
        {
            image:'7_6.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'true'
        },
        {
            image:'7_7.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'false'
        },
        {
            image:'7_8.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'false'
        },
        {
            image:'7_9.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'false'
        },
        {
            image:'7_10.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'false'
        },
        {
            image:'7_11.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'false'
        },
        {
            image:'9_slide.jpg',
            background:'7.jpg',
            hand:'7.png',
            istimer:'false'
        }
    ]
}